apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#common labels to apply
commonLabels:
  version: v1

#List of resource files that Kustomize reads, modifies and emits as a YAML string
resources:
- deployment.yaml
- route.yaml
- service.yaml